import type { IconString } from '@/components/Icon/types'

const iconMap: Record<string, IconString> = {
  '00': 'thin:sun',
  '01': 'thin:sun',
  '02': 'thin:cloud-sun',
  '03': 'thin:cloud-sun',
  '04': 'thin:cloud',
  '05': 'thin:cloud',
  '06': 'thin:cloud',
  '07': 'thin:cloud',
  '08': 'thin:cloud-rain',
  '09': 'thin:cloud-rain',
  '10': 'thin:cloud-rain',
  '11': 'thin:cloud-rain',
  '12': 'thin:cloud-rain',
  '13': 'thin:cloud-rain',
  '14': 'thin:cloud-rain',
  '15': 'thin:snowflake',
  '16': 'thin:snowflake',
  '17': 'thin:snowflake',
  '18': 'thin:snowflake',
  '19': 'thin:snowflake',
  '20': 'thin:cloud',
  '21': 'thin:cloud',
  '22': 'thin:cloud',
  '23': 'thin:cloud',
  '24': 'thin:cloud',
  '25': 'thin:cloud',
  '26': 'thin:cloud',
  '27': 'thin:cloud',
  '28': 'thin:cloud',
  '29': 'thin:cloud',
  '30': 'thin:cloud-sun',
  '31': 'thin:cloud',
  '32': 'thin:cloud',
  '33': 'thin:cloud',
  '34': 'thin:cloud',
  '35': 'thin:cloud',
  '36': 'thin:cloud',
  '37': 'thin:cloud',
  '38': 'thin:cloud',
  '39': 'thin:cloud-bolt',
  '40': 'thin:cloud-bolt',
  '41': 'thin:cloud-bolt',
  '42': 'thin:cloud-bolt',
  '43': 'thin:cloud-bolt',
  '44': 'thin:bolt',
  '45': 'thin:bolt',
  '46': 'thin:bolt',
  '47': 'thin:cloud-bolt',
}

export function getConditionIcon(code: string): IconString {
  return iconMap[code] ?? 'solid:cloud'
}
