import type { IconString } from '@/components/Icon/types'

const iconMap: Record<string, IconString> = {
  '00': 'solid:sun',
  '01': 'solid:sun',
  '02': 'solid:cloud-sun',
  '03': 'solid:cloud-sun',
  '04': 'solid:cloud',
  '05': 'solid:cloud',
  '06': 'solid:cloud',
  '07': 'solid:cloud',
  '08': 'solid:cloud-rain',
  '09': 'solid:cloud-rain',
  '10': 'solid:cloud-rain',
  '11': 'solid:cloud-rain',
  '12': 'solid:cloud-rain',
  '13': 'solid:cloud-rain',
  '14': 'solid:cloud-rain',
  '15': 'solid:snowflake',
  '16': 'solid:snowflake',
  '17': 'solid:snowflake',
  '18': 'solid:snowflake',
  '19': 'solid:snowflake',
  '20': 'solid:cloud',
  '21': 'solid:cloud',
  '22': 'solid:cloud',
  '23': 'solid:cloud',
  '24': 'solid:cloud',
  '25': 'solid:cloud',
  '26': 'solid:cloud',
  '27': 'solid:cloud',
  '28': 'solid:cloud',
  '29': 'solid:cloud',
  '30': 'solid:cloud-sun',
  '31': 'solid:cloud',
  '32': 'solid:cloud',
  '33': 'solid:cloud',
  '34': 'solid:cloud',
  '35': 'solid:cloud',
  '36': 'solid:cloud',
  '37': 'solid:cloud',
  '38': 'solid:cloud',
  '39': 'solid:cloud-bolt',
  '40': 'solid:cloud-bolt',
  '41': 'solid:cloud-bolt',
  '42': 'solid:cloud-bolt',
  '43': 'solid:cloud-bolt',
  '44': 'solid:bolt',
  '45': 'solid:bolt',
  '46': 'solid:bolt',
  '47': 'solid:cloud-bolt',
}

export function getConditionIcon(code: string): IconString {
  return iconMap[code] ?? 'solid:cloud'
}
