export const REFRESH_INTERVAL_MS = 15 * 60 * 1000
export const DEFAULT_SITE_CODE = 's0000403'
export const DEFAULT_PROVINCE = 'AB'
export const BURN_IN_ORBIT_RADIUS_PX = 5
export const BURN_IN_ORBIT_DURATION_MS = 60_000

export const FONT_AWESOME_ICON_STYLE = 'duotone-regular' as FontAwesomeIconStyle

export type FontAwesomeIconStyle =
  | 'chisel'
  | 'classic-light'
  | 'classic-regular'
  | 'classic-solid'
  | 'classic-thin'
  | 'duotone-light'
  | 'duotone-regular'
  | 'duotone-solid'
  | 'duotone-thin'
  | 'etch'
  | 'graphite'
  | 'jelly'
  | 'jelly-duo'
  | 'jelly-fill'
  | 'notdog'
  | 'notdog-duo'
  | 'sharp-duotone-light'
  | 'sharp-duotone-regular'
  | 'sharp-duotone-solid'
  | 'sharp-duotone-thin'
  | 'sharp-light'
  | 'sharp-regular'
  | 'sharp-solid'
  | 'sharp-thin'
  | 'slab'
  | 'slab-press'
  | 'thumbprint'
  | 'utility'
  | 'utility-duo'
  | 'utility-fill'
  | 'whiteboard'
